### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by qiweiii** [qiweiii/markdown-sticky-notes#45]
## Feature Requests

- [ ] migrate to mv3 #44 
- [ ] Export/import notes, by website or all notes
- [ ] Different style for hashtags (e.g. tag pills) #15 
- [ ] Scroll sync between editor and result #16
- [ ] Pin a note (fixed position in window)
- [ ] Supports save in SPA path
- [ ] Hotkeys/Shortcuts for creating notes #17 
- [ ] Improve styles of markdown result
- [ ] Publish to firefox
- [ ] Publish to edge
- [ ] Obsidian #13 #14 #30

Bugs
- [ ] Fix z-index problem on google developer
- [ ] Fix github issues page freeze
- [ ] Fix stackoverflow code css conflicts
- [ ] Fix possible css conflict on other sites that uses mui
